import turtle

turtle.speed(0)

turtle.penup()
turtle.goto(-400, 200)
turtle.pendown()
turtle.pencolor("red")
turtle.fillcolor("red")
turtle.begin_fill()
turtle.forward(800)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(800)
turtle.end_fill()

turtle.penup()
turtle.goto(-400, 100)
turtle.pendown()
turtle.pencolor("yellow")
turtle.fillcolor("yellow")
turtle.begin_fill()
turtle.forward(800)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(800)
turtle.end_fill()

turtle.penup()
turtle.goto(-400, 0)
turtle.pendown()
turtle.pencolor("blue")
turtle.fillcolor("blue")
turtle.begin_fill()
turtle.forward(800)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(800)
turtle.end_fill()

turtle.penup()
turtle.goto(-400, -100)
turtle.pendown()
turtle.pencolor("green")
turtle.fillcolor("green")
turtle.begin_fill()
turtle.forward(800)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(800)
turtle.end_fill()
